skr/config/routes.rb
KnackRegistry::Application.routes.draw do

  root :to => "registrant#home"

  match 'signin' => "registrant#login"
  match 'signout' => "registrant#logout"
  match 'signup' => "registrant#register"
  match 'give' => "registrant#give"

  match 'profile' => "registrant#profile"
  match 'transactions' => "registrant#viewall"
  match 'addgift' => "registrant#addgift"
  match 'links' => "registrant#links"
  match 'manage_registry' => "registrant#manage_registry"
  match 'invite_friends' => "follows#index"
  match 'fetch_fb_cross_friends' => "registrant#fetch_fb_cross_friends"
  match 'invited_signup' => 'registrant#invited_signup'

  match 'purchased' => redirect("/manage_registry")
  match 'wishlist' => redirect("/manage_registry")
  match 'ordered' => redirect("/manage_registry")

  match 'add_to_cart/:id' => "registrant#add_to_cart"
  match 'registrant/exchange/:id' => "registrant#exchange"

  match 'toolbars' => 'registrant#downloadtool'
  match 'add_my_gift' => 'registrant#addmyowngift', :as => 'add_my_gift'
  match 'use_toolbar' => 'registrant#how_use_toolbar'
  match 'calculate_tax' => 'registrant#calculate_tax'
  match 'delete_registry_item/:id' => 'registrant#delete_registry_item', :as => 'delete_registry_item'
  match 'edit_registry_item/:id' => 'registrant#edit_registry_item', :as => 'edit_registry_item'
  match 'add_from_registry/:id' => 'registrant#add_from_registry', :as => 'add_from_registry'

  match 'home' => redirect("/")
  match 'home2' => redirect("/")
  match 'home3' => redirect("/")
  match 'registrant/home' => redirect("/")
  match 'registry/:id' => 'registrant#registry', :as => 'registry'
  match 'catalog(/:id)' => 'browse#catalog', :as => 'catalog'
  match 'hot(/:site)' => 'browse#feed', :as => 'feed'

  match 'cart' => "payment#cart"
  get   'select_payment_method' => 'payment#select_payment_method'
  get   'pay_via_check' => 'payment#pay_via_check'
  get   'pay_via_venmo' => 'payment#pay_via_venmo'
  post  'make_payment_via_venmo' => 'payment#make_payment_via_venmo'
  match 'step1(/:id)' => "payment#step1", :as => "step1"
  match 'step2(/:id)' => "payment#step2", :as => 'step2'
  match 'step3' => "payment#step3"
  match 'process_order' => "payment#process_order"
  match 'success_payment/:guid' => "payment#success_payment", :as => "success_payment"
  match 'error_payment/:message' => "payment#error_payment", :as => "error_payment"
  match 'payment_interrupted' => "payment#payment_interrupted", :as => "payment_interrupted"

  scope 'item' do
    match ':c/:id(/:item_name)' => 'browse#item', :as => 'from_catalog'
    match ':r/:r2p/:id(/:item_name)' => 'browse#item', :as => 'from_registry'
  end

  match 'brands' => 'browse#brands'
  match 'brand/:valparam' => 'browse#catalog', :defaults => {:param => "b"}, :as => 'brand'
  match 'brand/:b/:id' => 'browse#item', :as => 'from_brand'

  match 'stores' => 'browse#stores'
  match 'store/:valparam' => 'browse#catalog', :defaults => {:param => "s"}, :as => 'store'
  match 'store/:s/:id' => 'browse#item', :as => 'from_store'

  match 'sf' => redirect("/sanfrancisco")
  match 'san_francisco' => redirect("/sanfrancisco")
  match 'sanfrancisco' => 'info#san_francisco'

  match 'info/sample_registry' => redirect("/sample_registry")
  match 'sample_registry' => 'registrant#registry', :defaults => {:id => 644}

  match 'info/howdoeswork' => redirect("/info/tour")

  resources :follows, :only => [:index, :create, :destroy, :follow_fb_friends]

  namespace :admin do
    resources :products, :except => :destroy do
      member do
        get :image
        put :image
      end
    end
    resources :partner_administrators do
      member do
        get :delete
      end
    end
  end

  match ':controller(/:action(/:id))'

end

skr/app/models/partner_administrator.rb
class PartnerAdministrator < ActiveRecord::Base
  belongs_to :partner
  
  validates :first_name,
                          :presence => {:message => "can't be blank"},
                          :length => {:minimum => 0, :maximum => 50}
  validates :last_name,
                          :presence => true,
                          :length => {:minimum => 0, :maximum => 50}
  validates :email,
                          :presence => true,
                          :email_format => true,
                          :length => {:minimum => 0, :maximum => 50},
                          :uniqueness => {:message => "This login is already in use", :case_sensitive => false}
  validates :new_password,
            :presence => {:on => :create},
            :length => {:minimum => 6, :maximum => 20, :on => :create}
  validates_length_of :new_password, :within => 6..20, :on => :update, :if => "change_password == '1'"

  validates :phone,
                          :length => {:minimum => 6, :maximum => 25}, 
                          :phone_format => {:message => "phone must be valid"},
                          :allow_blank => true

  attr_accessor :change_password
  attr_accessor :old_password
  attr_accessor :new_password

  before_update :do_password_change
  before_create :do_password_set

  def self.check_administrator(email, password)
    administrator = PartnerAdministrator.find_by_email_and_is_deleted(email.strip, false)
    if administrator.blank? || !PasswordUtilities.check(password.strip, administrator.password)
      return nil
    end
    administrator
  end

  protected

  def do_password_change
    if self.change_password == "1"
      if (!PasswordUtilities.check((old_password.strip||""), self.password))
        errors.add(:old_password, "Old password incorrect")
        return false
      else
        self.password = PasswordUtilities.hash(self.new_password.strip)
        self.change_password = nil
        self.old_password = nil
        self.new_password = nil
      end
    end
  end

  def do_password_set
    self.password = PasswordUtilities.hash(self.new_password.strip)
  end

end

skr/app/controllers/admin/partner_administrators_controller.rb
class Admin::PartnerAdministratorsController < ApplicationController
  layout "admin"
  before_filter :set_partner

  # GET /admin/administrators
  def index
    if @is_admin
      @administrators = PartnerAdministrator.paginate(:page => params[:page], :per_page => 50)
    else
      @administrators = @partner.partner_administrators.paginate(:page => params[:page], :per_page => 50)
    end
  end

  # GET /admin/products/new
  def new
    @administrator = PartnerAdministrator.new
  end

  # GET /admin/products/1
  def show
    redirect_to edit_admin_partner_administrator_path(params[:id])
  end

  # GET /admin/products/1/edit
  def edit
    if @is_admin
      @administrator = PartnerAdministrator.find(params[:id])
    else
      @administrator = @partner.partner_administrators.find(params[:id])
    end
  end

  # POST /admin/products
  def create
    if @is_admin
      @administrator = PartnerAdministrator.new(params[:partner_administrator])
    else
      @administrator = @partner.partner_administrators.build(params[:partner_administrator])
    end

    if @administrator.save
      flash.notice = "Administrator Created"
      redirect_to admin_partner_administrators_path
      return
    else
      render :new
    end
  end

  # PUT /admin/products/1
  def update
    if @is_admin
      @administrator = PartnerAdministrator.find(params[:id])
    else
      @administrator = @partner.partner_administrators.find(params[:id])
    end

    if @administrator.update_attributes(params[:partner_administrator])
      flash.notice = "Administrator Updated"
      redirect_to admin_partner_administrators_path
    else
      render :edit
    end
  end

  # Delete /admin/products/1
  def delete
    if @is_admin
      administrator = PartnerAdministrator.find(params[:id])
    else
      administrator = @partner.partner_administrators.find(params[:id])
    end

    if administrator.delete
      flash.notice = "Administrator Deleted"
    end

    redirect_to admin_partner_administrators_path
  end

  private

  def set_partner
    @partner = @current_partner
  end

end

skr/app/helpers/admin/partner_administrators_helper.rb
module Admin::PartnerAdministratorsHelper
end

skr/app/views/admin/partner_administrators/_form.html.erb
<script type="text/javascript">
    var controller = "<%= @is_admin ? "/administrative" : "/partner" %>";
</script>

<%= form_for([:admin, @administrator]) do |f| %>
    <div id="div-reg">
      <% if @is_admin %>
          <div class="div-block">
            <div class="editor-label">
              <label for="FirstName">Partner</label>
            </div>
            <div class="editor-field">
              <%= f.collection_select :partner_id, Partner.all, :id, :id%>
            </div>
            <div class="editor-error">
              <%= f.error_message_on :partner_id, :prepend_text => StaticDataUtilities.get_prepare_error_message %>
            </div>
          </div>
      <% end %>

      <%#*------------------------------%>
      <%#*FirstName%>
      <%#*------------------------------%>
      <div class="div-block">
        <div class="editor-label">
          <label for="FirstName">First Name *</label>
        </div>
        <div class="editor-field">
          <%= f.text_field :first_name%>
        </div>
        <div class="editor-error">
          <%= f.error_message_on :first_name, :prepend_text => StaticDataUtilities.get_prepare_error_message %>
        </div>
      </div>

      <%#*------------------------------%>
      <%#*LastName%>
      <%#*------------------------------%>
      <div class="div-block">
        <div class="editor-label">
          <label for="lastName">Last Name *</label>
        </div>
        <div class="editor-field">
          <%= f.text_field :last_name%>
        </div>
        <div class="editor-error">
          <%= f.error_message_on :last_name, :prepend_text => StaticDataUtilities.get_prepare_error_message %>
        </div>
      </div>


      <%#*------------------------------%>
      <%#*Login%>
      <%#*------------------------------%>
      <div class="div-block">
        <div class="editor-label">
          <label for="Login">Login(email) *</label>
        </div>
        <div class="editor-field">
          <%= f.text_field :email%>
        </div>
        <div class="editor-error">
          <%= f.error_message_on :email, :prepend_text => StaticDataUtilities.get_prepare_error_message %>
        </div>
      </div>

      <% if @administrator.id.blank? %>
          <%#*------------------------------%>
          <%#*Password%>
          <%#*------------------------------%>
          <div class="div-block">
            <div class="editor-label">
              <label for="Password">Password *</label>
            </div>
            <div class="editor-field">
              <%= f.password_field :new_password %>
            </div>
            <div class="editor-error">
              <%= f.error_message_on :new_password, :prepend_text => StaticDataUtilities.get_prepare_error_message  %>
            </div>
          </div>
      <% else %>

          <%#*------------------------------%>
          <%#*Set new password%>
          <%#*------------------------------%>
          <div class="div-block">
            <div class="editor-label">
              <label>Set new password </label>
            </div>
            <div class="editor-field">
              <%= f.check_box :change_password %>
            </div>
          </div>


          <div class="passwordBlock">
            <%#*------------------------------%>
            <%#*Old password%>
            <%#*------------------------------%>
            <div class="div-block">
              <div class="editor-label">
                <label for="OldPassword">Old password *</label>
              </div>
              <div class="editor-field">
                <%= f.password_field :old_password %>

              </div>
              <div class="editor-error">
                <%= f.error_message_on :old_password, :prepend_text => StaticDataUtilities.get_prepare_error_message  %>
              </div>
            </div>

            <%#*------------------------------%>
            <%#*New password%>
            <%#*------------------------------%>
            <div class="div-block">
              <div class="editor-label">
                <label for="NewPassword">New password *</label>
              </div>
              <div class="editor-field">
                <%= f.password_field :new_password %>
              </div>
              <div class="editor-error">
                <%= f.error_message_on :new_password, :prepend_text => StaticDataUtilities.get_prepare_error_message  %>
              </div>
            </div>

            <div class="emptyBlock">
            </div>
          </div>

      <% end %>

      <%#*------------------------------%>
      <%#*Phone%>
      <%#*------------------------------%>
      <div class="div-block">
        <div class="editor-label">
          <label for="Phone">Phone</label>
        </div>
        <div class="editor-field">
          <%= f.text_field :phone %>
        </div>
        <div class="editor-error">
          <%= f.error_message_on :phone, :prepend_text => StaticDataUtilities.get_prepare_error_message %>
        </div>
      </div>


      <%#*------------------------------%>
      <%#*Button%>
      <%#*------------------------------%>
      <div class="div-block">
        <div class="editor-label">
          <input type="hidden" value="d"/>
          <div class="emptyBlock"></div>
        </div>
        <div class="editor-field">
          <div class="btn-container">
            <%= button_to_function "", "document.location.assign('/partner/administrators')", :class => "btn-back" %>
            <%= f.submit :class => "btn-save" %>
          </div>
        </div>
        <div class="editor-error">
        </div>
      </div>
    </div>
<%end%>

skr/app/views/admin/partner_administrators/edit.html.erb
<% content_for :title do %>
    Administrator | Knack Registry
<% end %>
<% content_for :head do %>
    <%= javascript_include_tag "/javascripts/pages/Admin/knack.partner.administrator.js" %>
<%end%>

<% content_for :pagename do %>
    <div>
      Administrator
    </div>
<% end %>

<% content_for :registry do %>
    <div class="bl-block">
      <div class="blue-line">

      </div>
    </div>
<% end %>

<% content_for :background do %>
    <div class="bl-block">
      <div class="blue-line">
        <input type="hidden" value="fghj"/>
      </div>
    </div>
<% end %>

<div class="withBackground">
  <div class="content">
    <div class="mainBlock">
      <table cellpadding="0px" cellspacing="0px" border="0px">
        <tr>
          <td class="leftMenu">
            <%= render "administrative/left_menu" %>
          </td>
          <td class="rigthPane">

            <%=  show_flash %>
            <%= render "form" %>
          </td>
        </tr>
      </table>

    </div>
  </div>
</div>

skr/app/views/admin/partner_administrators/index.html.erb
<% content_for :title do %>
    Administrators
<% end %>
<% content_for :head do %>
    <%= stylesheet_link_tag "/stylesheets/Controls/Table.css" %>
    <%= stylesheet_link_tag "/stylesheets/Pages/Knack.Administrators.css" %>
    <%= javascript_include_tag "/javascripts/pages/Admin/knack.partner.administrator.js" %>

<%end%>
<% content_for :pagename do %>
    <div>Administrators</div>
<% end %>

<% content_for :registry do %>
    <div class="bl-block">
      <div class="blue-line">
        <div class="section-header">
        </div>
      </div>
    </div>
<% end %>

<% content_for :background do %>
    <div class="bl-block">
      <div class="blue-line">
        <input type="hidden" value="fghj"/>
      </div>
    </div>
<% end %>

<div class="withBackground">
  <div class="content">
    <div class="mainBlock">
      <div class="table-container">
        <%=  show_flash %>
        <table id="product-table" >
          <thead>
          <tr>
            <th class="id-column">Id</th>
            <% if @is_admin %>
                <th class="name-column">Partner</th>
            <% end  %>
            <th class="">First Name</th>
            <th class="">Last Name</th>
            <th class="">Email</th>
            <th class="">Phone</th>
            <th></th>
            <th></th>
          </tr>
          </thead>
          <tbody>
          <% @administrators.each do |admin| %>
              <tr>
                <td><%=  admin.id%></td>
                <% if @is_admin %>
                    <td><%=  admin.partner.BillingName + ' ' + admin.partner.BillingLastName %></td>
                <% end  %>
                <td><%=  admin.first_name %></td>
                <td><%=  admin.last_name %></td>
                <td><%=  admin.email %></td>
                <td><%=  admin.phone %></td>
                <td><%=  link_to 'Edit', edit_admin_partner_administrator_path(admin), :class => "edit"%></td>
                <td><%=  link_to 'Delete', delete_admin_partner_administrator_path(admin), :class => "delete", :confirm => 'Are you sure?', :method => :delete %></td>
              </tr>
          <%end%>
          </tbody>
        </table>
      </div>
    </div>
    <div class="div-button">
      <%= button_to(" ", new_admin_partner_administrator_path, :method => 'get', :class => 'btn-add') %>
    </div>
  </div>
</div>

skr/app/views/admin/partner_administrators/new.html.erb
<% content_for :title do %>
    Administrator | Knack Registry
<% end %>
<% content_for :head do %>
    <%= javascript_include_tag "/javascripts/pages/Admin/knack.partner.administrator.js" %>
<%end%>

<% content_for :pagename do %>
    <div>
      Administrator
    </div>
<% end %>

<% content_for :registry do %>
    <div class="bl-block">
      <div class="blue-line">

      </div>
    </div>
<% end %>

<% content_for :background do %>
    <div class="bl-block">
      <div class="blue-line">
        <input type="hidden" value="fghj"/>
      </div>
    </div>
<% end %>

<div class="withBackground">
  <div class="content">
    <div class="mainBlock">
      <table cellpadding="0px" cellspacing="0px" border="0px">
        <tr>
          <td class="leftMenu">
            <%= render "administrative/left_menu" %>
          </td>
          <td class="rigthPane">

            <%=  show_flash %>
            <%= render "form" %>
          </td>
        </tr>
      </table>

    </div>
  </div>
</div>