skr/config/routes.rb
KnackRegistry::Application.routes.draw do

  root :to => "registrant#home"

  match 'signin' => "registrant#login"
  match 'signout' => "registrant#logout"
  match 'signup' => "registrant#register"
  match 'give' => "registrant#give"

  match 'profile' => "registrant#profile"
  match 'transactions' => "registrant#viewall"
  match 'addgift' => "registrant#addgift"
  match 'links' => "registrant#links"
  match 'manage_registry' => "registrant#manage_registry"
  match 'invite_friends' => "follows#index"
  match 'fetch_fb_cross_friends' => "registrant#fetch_fb_cross_friends"
  match 'invited_signup' => 'registrant#invited_signup'

  match 'purchased' => redirect("/manage_registry")
  match 'wishlist' => redirect("/manage_registry")
  match 'ordered' => redirect("/manage_registry")

  match 'add_to_cart/:id' => "registrant#add_to_cart"
  match 'registrant/exchange/:id' => "registrant#exchange"

  match 'toolbars' => 'registrant#downloadtool'
  match 'add_my_gift' => 'registrant#addmyowngift', :as => 'add_my_gift'
  match 'use_toolbar' => 'registrant#how_use_toolbar'
  match 'calculate_tax' => 'registrant#calculate_tax'
  match 'delete_registry_item/:id' => 'registrant#delete_registry_item', :as => 'delete_registry_item'
  match 'edit_registry_item/:id' => 'registrant#edit_registry_item', :as => 'edit_registry_item'
  match 'add_from_registry/:id' => 'registrant#add_from_registry', :as => 'add_from_registry'

  match 'home' => redirect("/")
  match 'home2' => redirect("/")
  match 'home3' => redirect("/")
  match 'registrant/home' => redirect("/")
  match 'registry/:id' => 'registrant#registry', :as => 'registry'
  match 'catalog(/:id)' => 'browse#catalog', :as => 'catalog'
  match 'hot(/:site)' => 'browse#feed', :as => 'feed'

  match 'cart' => "payment#cart"
  get   'select_payment_method' => 'payment#select_payment_method'
  get   'pay_via_check' => 'payment#pay_via_check'
  get   'pay_via_venmo' => 'payment#pay_via_venmo'
  post  'make_payment_via_venmo' => 'payment#make_payment_via_venmo'
  match 'step1(/:id)' => "payment#step1", :as => "step1"
  match 'step2(/:id)' => "payment#step2", :as => 'step2'
  match 'step3' => "payment#step3"
  match 'process_order' => "payment#process_order"
  match 'success_payment/:guid' => "payment#success_payment", :as => "success_payment"
  match 'error_payment/:message' => "payment#error_payment", :as => "error_payment"
  match 'payment_interrupted' => "payment#payment_interrupted", :as => "payment_interrupted"

  scope 'item' do
    match ':c/:id(/:item_name)' => 'browse#item', :as => 'from_catalog'
    match ':r/:r2p/:id(/:item_name)' => 'browse#item', :as => 'from_registry'
  end

  match 'brands' => 'browse#brands'
  match 'brand/:valparam' => 'browse#catalog', :defaults => {:param => "b"}, :as => 'brand'
  match 'brand/:b/:id' => 'browse#item', :as => 'from_brand'

  match 'stores' => 'browse#stores'
  match 'store/:valparam' => 'browse#catalog', :defaults => {:param => "s"}, :as => 'store'
  match 'store/:s/:id' => 'browse#item', :as => 'from_store'

  match 'sf' => redirect("/sanfrancisco")
  match 'san_francisco' => redirect("/sanfrancisco")
  match 'sanfrancisco' => 'info#san_francisco'

  match 'info/sample_registry' => redirect("/sample_registry")
  match 'sample_registry' => 'registrant#registry', :defaults => {:id => 644}

  match 'info/howdoeswork' => redirect("/info/tour")

  resources :follows, :only => [:index, :create, :destroy, :follow_fb_friends]

  namespace :admin do
    resources :products, :except => :destroy do
      member do
        get :image
        put :image
      end
    end
    resources :partner_administrators do
      member do
        get :delete
      end
    end
  end

  match ':controller(/:action(/:id))'

end

skr/app/models/payment.rb
class Payment < ActiveRecord::Base
end

skr/app/controllers/payment_controller.rb
class PaymentController < ApplicationController
  skip_before_filter :check_out, [:select_payment_method, :pay_via_check, :pay_via_venmo]
  skip_before_filter :full_nav, [:select_payment_method, :pay_via_check, :pay_via_venmo]
  before_filter :create_venmo

  #######################################################
  # Action CART
  #######################################################
  def cart
    if request.post?
      if params[:quantityId].blank?
        redirect_to select_payment_method_path
        return
      end
    end

    unless params[:quantityId].blank? || params[:quantityValue].blank?
      quantity = (params[:quantityValue].to_i >= 1) ? params[:quantityValue].to_i : 1
      Cart.update_quantity_item(session, params[:quantityId], quantity)
    end

    @cart_information = Cart.get_full_information(session)
  end

  #######################################################
  # Action DELETE REGISTRY ITEM FROM CART
  #######################################################
  def deletefromcart
    unless params[:id].blank?
      Cart.delete_registry_item_from_cart(session, params[:id])
    end
    redirect_to cart_path
  end

  #######################################################
  # Action DELETE ITEM FROM CART
  #######################################################
  def deletefrombuycart
    unless params[:id].blank?
      Cart.delete_product_from_cart(session, params[:id])
    end
    redirect_to cart_path
  end

  #######################################################
  # Action DELETE CASH
  #######################################################
  def deletecash
    Cart.delete_cash(session)
    redirect_to cart_path
  end

  #######################################################
  # Action EMPTY CART
  #######################################################
  def emptycart
    Cart.empty_cart(session)
    redirect_to cart_path
  end

  def pay_via_venmo
    @cart_information = Cart.get_full_information(session)
    @venmo.store_access_token(params[:access_token])
  end

  def make_payment_via_venmo
    registrant = Registrant.find(params[:registrant_id])
    @cart_information = Cart.get_full_information(session)
    begin
      RegistryItem.transaction do
        registry_items = @cart_information.registry_items_for(registrant)
        order = Order.create_order(registrant, registry_items)
        @venmo.make_payment(params[:amount], registrant.Email, registrant.display_name) if Rails.env != 'development' || Rails.env != 'test'
        registry_items.each do |item|
          Cart.delete_registry_item_from_cart(session, item.id)
        end
      end
    rescue VenmoError => e
      flash[:error] = e.message
    end
    if Cart.is_empty_cart?(session)
      redirect_to root_path
    else
      redirect_to :back
    end
  end

  ##############################################################
  # ACTION error payment
  ##############################################################
  def error_payment
    notify_airbrake("Error in Payment " + params[:message])
    @result = params[:message]
  end

  ##############################################################
  # ACTION payment_interrupted
  ##############################################################
  def payment_interrupted
    @result = params[:message]
    render :error_payment
  end


  ##############################################################
  # ACTION success payment
  ##############################################################
  def success_payment
    #---------------------
    #- Checking for the existence of an order
    #---------------------
    if session[:order].blank? || params[:guid].blank?
      redirect_to payment_interrupted_path(:message => "The page was refreshed while your order was being processed. Please wait a few minutes and then check your email for an order confirmation.  If you did not receive a confirmation email please contact support@knackregistry.com")
      return
    else
      order = session[:order]
      unless order.GUID == params[:guid]
        redirect_to error_payment_path("Invalid in success_payment")
        return
      end
    end

    # set status and date
    order.OrdersStatus_ID = OrdersStatus::STATUSES.invert['New']
    order.DateTime = DateTime.now

    # get information about order
    cart = Cart.get_cart(session)
    cart_information = Cart.get_full_information(session)
    payment_info = session[:payment_info]

    if session[:registrant].blank? # how not authenticated user
      order.save

      # BUY A PRODUCT FOR A NON AUTHENTICATED USER
      cart.products.each do |item|
        unless order.buy_item_himself(item)
          redirect_to error_payment_path(ErrorMessages.get_text_error(0))
          return
        else
          expire_brands_cache if Product.find_by_id(item.id).IsKind
        end
      end

      # CONTRIBUTE TO A REGISTRY GIFT
      cart.registry_items.each do |item|
        unless order.buy_item_someone(item)
          redirect_to error_payment_path(ErrorMessages.get_text_error(0))
          return
        end
      end
    else # authorized user
      order.registrant_id = registrant.id
      order.save

      cart.registry_items.each do |item|
        # Get money from queue
        if payment_info.use_cash
          if item.total > RegistryItem.find_by_id(item.id).Contributed
            unless order.use_cash_money(item, registrant, 'registry item')
              redirect_to error_payment_path(ErrorMessages.get_text_error(0))
              return
            end
          end
        else
          if item.type == BuyRegistryItem::ORDER || item.type == BuyRegistryItem::BUY_REGISTRANT_FROM_REGISTRY
            registrant.update_attribute(:Cash, registrant.Cash.to_f + RegistryItem.find_by_id(item.id).Contributed)
          end
        end

        case item.type
        when BuyRegistryItem::ORDER
          unless order.buy_from_registry(item)
            redirect_to error_payment_path(ErrorMessages.get_text_error(0))
            return
          end
        when BuyRegistryItem::BUY_REGISTRANT_FROM_REGISTRY
          unless order.buy_from_registry(item)
            redirect_to error_payment_path(ErrorMessages.get_text_error(0))
            return
          end
        when BuyRegistryItem::CONTRIBUTE
          unless order.buy_item_someone(item)
            redirect_to error_payment_path(ErrorMessages.get_text_error(0))
            return
          end
        end
      end

      # BUY FOR HIMSELF
      cart.products.each do |item|
        # Get money from queue
        if payment_info.use_cash
          unless order.use_cash_money(item, registrant, 'product')
            redirect_to error_payment_path(ErrorMessages.get_text_error(0))
            return
          end
        end

        # BUY FOR HIMSELF
        unless order.buy_item_himself(item)
          redirect_to error_payment_path(ErrorMessages.get_text_error(0))
          return
        else
          expire_brands_cache if Product.find_by_id(item.id).IsKind
        end
      end

      # GET CASH
      if cart_information.type == CartInformation::TYPE_WITHDRAW
        # UPDATE RECORD ABOUT PRODUCT IN REGISTRY ITEM
        # For each item being exchanged for cash
        cart.withdraw_ids.each do |id|
          unless order.exchange(id)
            redirect_to error_payment_path(ErrorMessages.get_text_error(0))
            return
          end
        end

        # We do not allow users to withdraw from credit at the moment, but this is going to come up, and will need to be added back in.
        # If the user has decided to withdraw some cash.
        #if cart.Cash.IsCash
        #  unless order.withdraw_from_cash(registrant)
        #    redirect_to error_payment_path(ErrorMessages.get_text_error(0))
        #    return
        #  end
        #end
      end
    end

    # Clear out payment_info and the cart
    Cart.clear_session(session)
    # Send an email confirming the order
    MailUtilities.send_order(order) unless cart_information.type == CartInformation::TYPE_WITHDRAW
    @transaction = Transactions.get_transaction(order)

    unless registrant.blank?
      @queue = registrant.get_queue
    end
  end

  ##############################################################
  # ACTION process_order
  ##############################################################
  def process_order
    if Cart.is_empty_cart?(session)
      redirect_to cart_path
      return
    end

    if session[:order].blank?   # Get the order, or error out if it's not set.
      redirect_to cart_path
      return
    else
      order = session[:order]
    end

    @cart_information = Cart.get_full_information(session)
    @payment_info = session[:payment_info]

    if session[:registrant].blank? # If this is not a logged in user,
      amount = @cart_information.total
    else                          # If this is a registered user.
      if @payment_info.use_cash
        amount = @cart_information.queue > @cart_information.total ? 0 : @cart_information.total - @cart_information.queue
      else
        amount = @cart_information.total
      end

      session[:order].TakeMoneyAmount = @cart_information.total - amount
    end

    # At this point.
    # cart has been set.
    # amount has been set to the total amount minus any money being taken from credit.
    # Sub-totals have ben set for tax and shiping etc...
    # TakeAmountMoney in the order in the session has been set to the amount taken from credit.

    amount *=  100

    case @payment_info.type_payment
    when PaymentInfo::TYPE_PAYMENT.invert['cash']
      redirect_to success_payment_path(order.GUID)
    when PaymentInfo::TYPE_PAYMENT.invert['credit card']
      begin
        card = ActiveMerchant::Billing::CreditCard.new(
          :number => @payment_info.card_number,
          :month => @payment_info.card_exp_month,
          :year => @payment_info.card_exp_year,
          :first_name => @payment_info.first_name,

skr/app/helpers/payment_helper.rb
module PaymentHelper
end

skr/app/views/payment/_buy_contribute_summary.html.erb
<%#*Sub-total%>
<tr>
  <td></td>
  <td class="rightColumn">Sub-Total: <span class="price"><%= formatted_price(@cart_information.subtotal) %></span></td>
</tr>


<%#*Estimated Shipping%>
<% if @cart_information.shipment_total > 0 %>
  <tr>
    <td></td>
    <td class="rightColumn">Shipping: <span class="price"><%= formatted_price(@cart_information.shipment_total) %></span></td>
  </tr>
<% end %>

<%#*Tax%>
<% if @cart_information.tax_total > 0 %>
    <tr>
      <td></td>
      <td class="rightColumn">Sales Tax: <span class="price"><%= formatted_price(@cart_information.tax_total) %></span></td>
    </tr>
<% end %>

skr/app/views/payment/_empty_tr.html.erb
<tr>
  <td></td>
  <td><input type="button" style="visibility: hidden" value="sdf"/></td>
</tr>

skr/app/views/payment/_item_thumbnail.html.erb
<div class="div-block-item">
  <%#*Item image%>
  <div class="image-div">
    <%= image_tag image,
                  :alt => product_name,
                  :class => "product-image-small" %>
  </div>
  <div class="details-div">
    <%#*Item name%>
    <div class="productName">
      <%= product_name -%>
    </div>

    <%#*Item amount%>
    <div class="div-items-amount">
      <%= formatted_price(subtotal) %>
    </div>
  </div>
</div>

skr/app/views/payment/_order_summary.html.erb
<% case @cart_information.type %>
<% when CartInformation::TYPE_BUY_CONTRIBUTE %>
    <%= render 'buy_contribute_summary'%>
<% when CartInformation::TYPE_WITHDRAW %>
    <tr>
      <td></td>
      <td class="rightColumn">Withdraw cash subtotal <span class="price"><%= formatted_price(@cart_information.withdraw_total) %></span></td>
    </tr>

    <% if @cart_information.commission > 0 %>
        <tr>
          <td></td>
          <td class="rightColumn">Knack fee: <span class="price"><%= formatted_price(@cart_information.commission) %></span></td>
        </tr>
    <% end %>
<% end %>

<%= render "empty_tr" %>

<%#*Total%>
<% if @cart_information.total > 0 %>
    <tr>
      <td></td>
      <td class="rightColumn">Total: <span class="price"><%= formatted_price(@cart_information.total) %></span></td>
    </tr>
<% end %>

<%= render "empty_tr" %>

<%#*Queue Info%>
<% if @cart_information.use_cash && @cart_information.queue && @cart_information.queue > 0 && @cart_information.total && @cart_information.total > 0  &&  @cart_information.type != CartInformation::TYPE_WITHDRAW %>
    <tr>
      <td></td>
      <td class="rightColumn">Knack Credit: <span class="price"><%= formatted_price((@cart_information.queue)) %></span></td>
    </tr>

<%#*Additional payment%>
    <% if @cart_information.missing_amount < 0  %>
        <tr>
          <td></td>
          <td class="rightColumn">Required Payment: <span class="price"><%= formatted_price((@cart_information.missing_amount * -1)) %></span></td>
        </tr>

    <% else %>
        <tr>
          <td></td>
          <td class="rightColumn">Required Payment: <span class="price"><%= formatted_price(0.0) %></span></td>
        </tr>
    <% end %>
<% end %>

skr/app/views/payment/error_payment.html.erb
<%= h @result %>

skr/app/views/payment/pay_via_venmo.html.erb
<% content_for :title do %>
  Pay via Venmo
<% end %>

<% unless @venmo.authorized? %>
  <%= link_to 'Authorize us on Venmo', @venmo.authorize_url(pay_via_venmo_url) %>
<% else %>
  <%= form_tag 'make_payment_via_venmo' do %>
    <% @cart_information.registry_items_by_registrant.each do |registrant, items| %>
      <dl>
        <% amount = items.map(&:contribute).sum %>
        <%= hidden_field_tag :amount, amount %>
        <%= hidden_field_tag :registrant_id, registrant.id %>
        <dt><%= label_tag "Amount" %></dt>
        <dd><%= label_tag number_to_currency(amount) %></dd>
        <dt><%= label_tag "Recipient" %></dt>
        <dd><%= label_tag registrant.display_name %><dd>
        <%= submit_tag 'Make Payment' %>
      </dl>
    <% end %>
  <% end %>
<% end %>

skr/app/views/payment/process_payment.html.erb
<%#*<form action="https://www.paypal.com/cgi-bin/webscr" method="post">%>
  <%#*<!-- Identify your business so that you can collect the payments. -->%>
  <%#*<input type="hidden" name="business" value="herschelgomez@xyzzyu.com"/>%>
  <%#*<!-- Specify a Buy Now button. -->%>
  <%#*<input type="hidden" name="cmd" value="_xclick"/>%>
  <%#*<!-- Specify details about the item that buyers will purchase. -->%>
  <%#*<input type="hidden" name="item_name" value="Hot Sauce-12 oz. Bottle"/>%>
  <%#*<input type="hidden" name="amount" value="5.95"/>%>
  <%#*<input type="hidden" name="currency_code" value="USD"/>%>
  <%#*<!-- Prompt buyers to enter their desired quantities. -->%>
  <%#*<input type="hidden" name="undefined_quantity" value="1"/>%>
  <%#*<!-- Display the payment button. -->%>
  <%#*<input type="image" name="submit" border="0"%>
  <%#*src="https://www.paypal.com/en_US/i/btn/btn_buynow_LG.gif"%>
  <%#*alt="PayPal - The safer, easier way to pay online"/>%>
  <%#*<img alt="" border="0" width="1" height="1"%>
  <%#*src="https://www.paypal.com/en_US/i/scr/pixel.gif" />%>
<%#*</form>%>
  <%= h @result %>

skr/app/views/payment/select_payment_method.html.erb
<% content_for :title do %>
  Select Payment Method
<% end %>

<h3>Please select the payment method you would like to use</h3>
<table id="tbl-payment-method">
  <tbody>
    <tr>
      <td>
        <div class="pay-block" id="pay-via-venmo">
          <div class="in-block">
            <p><span id="spn-venmo">Pay via Venmo</span></p>
            <p><span class="spn-text-in">Use the Venmo service to securely pay online.</span></p>
          </div>
          <a href="<%= pay_via_venmo_path %>">
            <div class="btn-in-block" id="div-btn-venmo">
              <span>PAY VIA VENMO</span>
            </div>
          </a>
        </div>
      </td>
      <td>
        <div class="pay-block" id="find-registry">
          <div class="in-block">
            <p><span id="spn-check">Pay via Check</span></p>
            <p><span class="spn-text-in">Pay using the old-fashioned method of mailing a check.</span></p>
          </div>
          <a href="<%= pay_via_check_path %>">
            <div class="btn-in-block">
              <span>PAY VIA CHECK</span>
            </div>
          </a>
        </div>
      </td>
    </tr>
  </tbody>
</table>

skr/app/views/payment/step3.html.erb
<% content_for :title do %>
  Confirm Order | Knack Registry
<% end %>
<% content_for :head do %>
  <%= stylesheet_link_tag "/stylesheets/layouts/Cart.css" %>
  <%= stylesheet_link_tag "/stylesheets/Pages/Step3.css" %>
  <%= javascript_include_tag "/javascripts/knack.payment.step3.js"  %>
<%end%>

<div class="div-c">
  <div class="topMenu">
    <div class="pageName">
      Checkout
    </div>
    <div class="div-link-step">
			<%= link_to "1. Billing Information", step1_path %>
			<%= link_to "2. Payment Information", step2_path %>
			<b><%= link_to "3. Confirm Order", step3_path%></b>
    </div>
  </div>
  <div class="withBackground">
    <div class="content">
      <%=  show_flash %>
      <div class="mainBlock">
        <div id="line-header" class="Line"></div>
        <table id="table-payment">
          <tr>
            <%#*----------------------------%>
            <%#*Left column%>
            <%#*----------------------------%>
            <td class="leftTD">
              <div class="div-header-conf">
                <span class="header-column">Confirm Order Information</span>
              </div>

              <div class="div-items">
                <%= form_tag process_order_path, :id => "frm-order" do %>
                  <div class="div-header-item">
                    <span class="header-column">Items</span>
                  </div>
                    <% if @cart_information.type == CartInformation::TYPE_WITHDRAW %>
                        <%= render 'item_thumbnail', :image => 'cash.png', :product_name => 'Withdraw cash', :subtotal => @cart_information.withdraw_total %>
                    <% else %>
                        <% @cart_information.list_registry_items.each do |registry_item| %>
                            <%= render 'item_thumbnail', :image => registry_item.main_product_thumb_url_small, :product_name => registry_item.product_name, :subtotal => registry_item.subtotal %>
                        <% end %>

                        <% @cart_information.list_products.each do |item| %>
                            <%= render 'item_thumbnail', :image => item.main_product_thumb_url_small, :product_name => item.product_name, :subtotal => item.subtotal %>
                        <% end %>
                    <% end %>
                <% end %>
              </div>
            </td>

            <%#*----------------------------%>
            <%#*Center column%>
            <%#*----------------------------%>
            <td class="centerTD">
              <div class="div-center-block">
                <div class="div-header-item">
                  <span class="header-column">Billing Address</span>
                </div>

                <div class="info-container">
                  <div class="info-block">
                    <%#*----------------------------%>
                    <%#*Billing Name%>
                    <%#*----------------------------%>
                    <div class="info-name">
                      <%= @order.BillingFirstName %> <%= @order.BillingLastName %>
                    </div>

                    <%#*----------------------------%>
                    <%#*Billing Address%>
                    <%#*----------------------------%>
                    <div class="info-address">
                      <%= @order.BillingAddress %>
                    </div>

                    <%#*----------------------------%>
                    <%#*Billing City, State%>
                    <%#*----------------------------%>
                    <div class="info-cs">
                      <%= @order.BillingCity %>, <%= @order.billing_state_name %>
                    </div>

                    <%#*----------------------------%>
                    <%#*Billing ZIP%>
                    <%#*----------------------------%>
                    <div class="info-zip">
                      <%= @order.BillingZip %>
                    </div>
                  </div>
                  
                  <%#*----------------------------%>
                  <%#*Billing Edit%>
                  <%#*----------------------------%>
                  <div class="bill-edit">
										<%= link_to "Edit", step1_path(1) %>
                  </div>
                </div>

                <% if Cart.is_buy?(Cart.get_cart(session)) %>
                  <div class="div-header-item">
                    <span class="header-column">Shipping Address</span>
                  </div>
 
                  <div class="info-container">
                  	<div class="info-block">
	                    <%#*----------------------------%>
	                    <%#*Shipping Name%>
	                    <%#*----------------------------%>
	                    <div class="info-name">
	                      <%= @order.ShippingFirstName %> <%= @order.ShippingLastName %>
	                    </div>

	                    <%#*----------------------------%>
	                    <%#*Shipping Address%>
	                    <%#*----------------------------%>
	                    <div class="info-address">
	                      <%= @order.ShippingAddress %>
	                    </div>

	                    <%#*----------------------------%>
	                    <%#*Shipping City, State%>
	                    <%#*----------------------------%>
	                    <div class="info-cs">
	                      <%= @order.ShippingCity %>, <%= @order.shipping_state_name %>
	                    </div>

	                    <%#*----------------------------%>
	                    <%#*Shipping ZIP%>
	                    <%#*----------------------------%>
	                    <div class="info-zip">
	                      <%= @order.ShippingZip %>
	                    </div>
	                  </div>

                  <%#*----------------------------%>
                  <%#*Shipping Edit%>
                  <%#*----------------------------%>
                  <div class="bill-edit">
										<%= link_to "Edit", step1_path(1) %>
                  </div>
                </div>
                <% end %>

                <div class="div-header-item">
                  <span class="header-column">Payment Method</span>
                </div>

                <div class="info-container">
                  <div class="info-block">
										<% case @payment_info.type_payment %>
											<% when PaymentInfo::TYPE_PAYMENT.invert['cash'] %>
												Knack Credit
											<% when PaymentInfo::TYPE_PAYMENT.invert['credit card'] %>
                        <%#*Type creditcard%>
                        <div class="info-name">
                          <%= @payment_info.card_type %>
                        </div>

                        <%#*Number creditcard%>
                        <div class="info-address">
                          <% card_number = @payment_info.card_number[@payment_info.card_number.length - 4, @payment_info.card_number.length - 1] %>
													<%= 'X'*(@payment_info.card_number.length - 4) << card_number %>
                        </div>

                        <%#*Name creditcard%>
                        <div class="info-cs">
                          <%= @payment_info.first_name %> <%= @payment_info.last_name %>
                        </div>
											<% when PaymentInfo::TYPE_PAYMENT.invert['buy paypal'] %>
                        <div class="info-name">
                          PayPal
                        </div>
											<% when PaymentInfo::TYPE_PAYMENT.invert['withdraw paypal'] %>
												<div class="info-name">
                          PayPal: <%= @payment_info.paypal_email %>
                        </div>
											<% when PaymentInfo::TYPE_PAYMENT.invert['check'] %>
												<div class="info-name">
                          Check
                        </div>
										<% end %>
                  </div>

                  <%#*----------------------------%>
                  <%#*Payment Edit%>
                  <%#*----------------------------%>
                  <div class="bill-edit">
										<%= link_to "Edit", step2_path(1) %>
                  </div>
                </div>
              </div>
            </td>

            <%#*----------------------------%>
            <%#*Right column%>
            <%#*----------------------------%>
            <td class="rightTD">
              <div class="order-summary">
                <span class="header-column">
                  Order Summary
                </span>
              </div>

              <table id="amount">
                <tbody>
									<%= render 'order_summary' %>
                </tbody>
              </table>
            </td>
          </tr>
        </table>

        <div class="div-btn">
          <input type="button" class="btn-process" value=""/>
        </div>
      </div>
    </div>
  </div>
</div>