skr/config/routes.rb
KnackRegistry::Application.routes.draw do

  root :to => "registrant#home"

  match 'signin' => "registrant#login"
  match 'signout' => "registrant#logout"
  match 'signup' => "registrant#register"
  match 'give' => "registrant#give"

  match 'profile' => "registrant#profile"
  match 'transactions' => "registrant#viewall"
  match 'addgift' => "registrant#addgift"
  match 'links' => "registrant#links"
  match 'manage_registry' => "registrant#manage_registry"
  match 'invite_friends' => "follows#index"
  match 'fetch_fb_cross_friends' => "registrant#fetch_fb_cross_friends"
  match 'invited_signup' => 'registrant#invited_signup'

  match 'purchased' => redirect("/manage_registry")
  match 'wishlist' => redirect("/manage_registry")
  match 'ordered' => redirect("/manage_registry")

  match 'add_to_cart/:id' => "registrant#add_to_cart"
  match 'registrant/exchange/:id' => "registrant#exchange"

  match 'toolbars' => 'registrant#downloadtool'
  match 'add_my_gift' => 'registrant#addmyowngift', :as => 'add_my_gift'
  match 'use_toolbar' => 'registrant#how_use_toolbar'
  match 'calculate_tax' => 'registrant#calculate_tax'
  match 'delete_registry_item/:id' => 'registrant#delete_registry_item', :as => 'delete_registry_item'
  match 'edit_registry_item/:id' => 'registrant#edit_registry_item', :as => 'edit_registry_item'
  match 'add_from_registry/:id' => 'registrant#add_from_registry', :as => 'add_from_registry'

  match 'home' => redirect("/")
  match 'home2' => redirect("/")
  match 'home3' => redirect("/")
  match 'registrant/home' => redirect("/")
  match 'registry/:id' => 'registrant#registry', :as => 'registry'
  match 'catalog(/:id)' => 'browse#catalog', :as => 'catalog'
  match 'hot(/:site)' => 'browse#feed', :as => 'feed'

  match 'cart' => "payment#cart"
  get   'select_payment_method' => 'payment#select_payment_method'
  get   'pay_via_check' => 'payment#pay_via_check'
  get   'pay_via_venmo' => 'payment#pay_via_venmo'
  post  'make_payment_via_venmo' => 'payment#make_payment_via_venmo'
  match 'step1(/:id)' => "payment#step1", :as => "step1"
  match 'step2(/:id)' => "payment#step2", :as => 'step2'
  match 'step3' => "payment#step3"
  match 'process_order' => "payment#process_order"
  match 'success_payment/:guid' => "payment#success_payment", :as => "success_payment"
  match 'error_payment/:message' => "payment#error_payment", :as => "error_payment"
  match 'payment_interrupted' => "payment#payment_interrupted", :as => "payment_interrupted"

  scope 'item' do
    match ':c/:id(/:item_name)' => 'browse#item', :as => 'from_catalog'
    match ':r/:r2p/:id(/:item_name)' => 'browse#item', :as => 'from_registry'
  end

  match 'brands' => 'browse#brands'
  match 'brand/:valparam' => 'browse#catalog', :defaults => {:param => "b"}, :as => 'brand'
  match 'brand/:b/:id' => 'browse#item', :as => 'from_brand'

  match 'stores' => 'browse#stores'
  match 'store/:valparam' => 'browse#catalog', :defaults => {:param => "s"}, :as => 'store'
  match 'store/:s/:id' => 'browse#item', :as => 'from_store'

  match 'sf' => redirect("/sanfrancisco")
  match 'san_francisco' => redirect("/sanfrancisco")
  match 'sanfrancisco' => 'info#san_francisco'

  match 'info/sample_registry' => redirect("/sample_registry")
  match 'sample_registry' => 'registrant#registry', :defaults => {:id => 644}

  match 'info/howdoeswork' => redirect("/info/tour")

  resources :follows, :only => [:index, :create, :destroy, :follow_fb_friends]

  namespace :admin do
    resources :products, :except => :destroy do
      member do
        get :image
        put :image
      end
    end
    resources :partner_administrators do
      member do
        get :delete
      end
    end
  end

  match ':controller(/:action(/:id))'

end

skr/app/models/registrant_type.rb
class RegistrantType < ActiveRecord::Base
  validates_uniqueness_of :Name
end

skr/app/controllers/registrant_controller.rb
require 'mail_utilities'
require 'cart'
require 'math_utilite'
require 'uri'
require 'net/http'
class RegistrantController < ApplicationController

  def upload_image
    @registrant = registrant
    unless request.get?
      @call = "upload_image"
      if @registrant.update_attributes(params[:registrant])
        @status = "true"
        @param = "/registrant/crop_image"
      else
        @status = "false"
        @param = "The image must be a JPG, JPEG or PNG under 3 MB."
      end
      render 'shared/close_modal', :layout => "empty"
      return
    end
    render 'shared/upload_image', :layout => "empty", :locals => {:model => @registrant,  :attachment => :profile_image}
  end

  def crop_image
    @registrant = registrant
    unless request.get?
      @call = "crop_image"
      if @registrant.update_attributes(params[:registrant])
        @status = "true"
        @param = @registrant.profile_image.url(:large)
      else
        @status = "false"
        @param = @registrant.errors.to_s
      end
      render 'shared/close_modal', :layout => "empty"
      return
    end
    render 'shared/crop_image', :layout => "empty", :locals => {:model => @registrant,  :attachment => :profile_image, :action => "crop_image"}
  end

  def crop_product_image
    product = registrant.owned_products.find(params[:id])
    unless request.get?
      @call = "crop_image"
      if product.update_attributes(params[:product])
        @status = "true"
        @param = '/manage_registry'
      else
        @status = "false"
        @param = product.errors.to_s
      end
      render 'shared/close_modal', :layout => "empty"
      return
    end
    render 'shared/crop_image', :layout => "empty", :locals => {:model => product,  :attachment => :main_product_thumb, :action => "crop_product_image"}
  end


  #######################################################
  # Action HOME
  #######################################################
  def home
    render :home, :layout => "application"
  end

  #######################################################
  # Action HOME2 used for A/B Testing
  #######################################################
  def home2
    render :home2, :layout => "application"
  end

  #######################################################
  # Action HOME
  #######################################################
  def activation
    @registrant = Registrant.activate params[:id]
    unless @registrant.blank?
      MailUtilities.send_activated(@registrant.Email, @registrant.Email)
    end
  end

  #######################################################
  # Action confirm
  #######################################################
  def confirm
    @email = params[:email]
  end

  #######################################################
  # Action GIVE
  #######################################################
  def give
    @registry = ''

    unless params[:find].blank?
      @isPost = 1

      @registry = params[:find].blank? ? '' : params[:find].to_s

      @registrants = Registrant.search(@registry, params[:page], 10)
    end
  end

  #######################################################
  # Action list_registries_for_google
  #######################################################
  def list_registries_for_google
    @registrants = Registrant.active.paginate(:page => params[:page])
  end

  #######################################################
  # Action MANAGE REGISTRY
  #######################################################
  def manage_registry

    # Do not cache this page.
    response.headers["Cache-Control"] = "no-cache, no-store, max-age=0, must-revalidate"
    response.headers["Pragma"] = "no-cache"
    response.headers["Expires"] = "Fri, 01 Jan 1990 00:00:00 GMT"

    @registrant = registrant

    sort = (params[:sort] || 0).to_i
    filter = (params[:filter] || "0").to_i

    manage_registry_params = ManageRegistryParams.new(params[:page], nil, sort, filter)

    if request.post? && !params[:back_view].blank?
      unless session[:manage_registry_params].blank?
        manage_registry_params = session[:manage_registry_params]
      end
    end
    session[:manage_registry_params] = manage_registry_params
    session[:back_path] = manage_registry_path(:filter => manage_registry_params.filter, :sort => manage_registry_params.sort, :page => manage_registry_params.page)

    @registrant2products = registrant.gifts(manage_registry_params.filter, manage_registry_params.page, manage_registry_params.per_page, manage_registry_params.sort)

  end

  #######################################################
  # Action update_all_external
  #######################################################
  def update_external
    @valid = true
    @products = registrant.registry_items.not_catalog.editable.collect do |item|
      item.product
    end
    unless request.get?
      if params[:products].blank?
        @products = []
        @valid = true
        return
      end
      params[:products].keys.each do |id|
        prod = Product.find(id)
        raise ActiveRecord::RecordNotFound if prod.Registrant_ID != registrant.id
      end

      @products = Product.update(params[:products].keys, params[:products].values)
      @products.each do |p|
        @valid = false unless p.errors.empty?
      end

      if @valid
        flash.notice = "Changes Saved"
        redirect_to "/registrant/update_external"
      end
    end
  end

  #######################################################
  # Action ViewAll
  #######################################################
  def viewall
    @transactions = Transactions.get_transactions(session[:registrant])

    @registrant = registrant

    #################################
    #Pager
    #################################
    @pager = Pager.new(params[:countP], @transactions.length, params[:currentP])
    @transactions = Pager.get_array(@pager.page_size, @transactions, 1, @pager.offset)
  end

  #######################################################
  # Action AddGift
  #######################################################
  def addgift
    @registrant = registrant
    @is_new = !params[:new_user].blank?
  end

  #######################################################
  # Action ADDMYOWNGIFT
  #######################################################
  def addmyowngift

    if request.post?
      @item = RegistryItem.new(params[:registry_item])
      @item.registrant = registrant
      @item.Price = @item.product.MasterPrice
      @item.Purchased_ID = RegistryItem::AVAILABLE

      @item.product.creator = registrant

      if @item.save
        @status = true
        @call = @item.product.stock_image.blank? ? "addmyowngift" : "crop_image"
        @param = @item.product.stock_image.blank? ? "/registrant/crop_product_image/#{@item.product.id}" : "/manage_registry"
        render 'shared/close_modal', :layout => false
        return
      end
    else
      @item = RegistryItem.new
      @item.product = Product.new(:MasterPrice => 1)
    end

    render :addmyowngift, :layout => 'empty'
  end

  #######################################################
  # Action DOWNLOADTOOL
  #######################################################
  def downloadtool
    @registrant = registrant

    @browsers = [
        Browsers.new(1, 'Internet Explorer', 'toolbar_ie'),
        Browsers.new(2, 'Chrome', 'toolbar_cr'),
        Browsers.new(3, 'Firefox', 'toolbar_ff'),
        Browsers.new(4, 'Safari', 'toolbar_safari')
    ]
    @browser = @browsers.first
    if !params[:browser].blank? && !params[:browser][:id].blank?
      @browser = @browsers.find{|b| b.id == params[:browser][:id].to_i}
    end

    render :downloadtool, :layout => 'empty'
  end

  #######################################################
  # Action REGISTRY
  #######################################################
  def registry
    if session[:registrant]
      @registrant = registrant
    end
    @registry = Registrant.includes(:sections, :registry_items => [:product, :contributes]).find_by_id_and_IsDeleted(params[:id], false)

    if @registry.blank?
      redirect_to :controller => :registrant, :action => :give
      return
    end

    session[:back_path]=registry_path(:id => @registry.id)

    if request.put? && @registrant == @registry
      if @registry.update_attributes(params[:registrant])
        # If something was moved to a newly create section update attributes will not automatically deal with it.
        unless params["registrant"]["registry_items_attributes"].blank?
          params["registrant"]["registry_items_attributes"].each_value do |i|
            if i["section_id"] == ""
              reg_item = RegistryItem.find(i["id"])
              reg_item.section = @registry.sections.where(:order => i["section_order"]).first
              reg_item.save
            end
          end
        end
        reset_registrant
        redirect_to :action => :registry, :id => params[:id]
      end
    end

    if @registrant.nil? # When viewing a registry as a not logged in user remove the nav bar.
      session[:full_nav] = false
    end
  end

  #######################################################
  # Action EDIT REGISTRY ITEM
  #######################################################
  def edit_registry_item
    @reg_item = registrant.registry_items.find(params[:id])
    raise "Item not found" if @reg_item.nil? || @reg_item.IsDeleted?

    if request.put?
      unless @reg_item.update_attributes(params[:registry_item])
        render :layout => "buy", :status => :bad_request
        return
      end
      product_params = params[:product_params]

      unless product_params.blank?
        @reg_item.reset_params(product_params)
      end

      @status = 5
      @param = @reg_item.id
      render 'shared/close_modal', :layout => false

    else
      render :layout => "buy"
    end
  end

  def invited_signup
    @registrant = registrant
  end

  #######################################################

skr/app/helpers/registrant_helper.rb
module RegistrantHelper
  def link_to_add_fields(name, f, association)
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
      render(association.to_s.singularize + "_fields", :f => builder)
    end
    link_to_function(name, h("add_fields(this, '#{association}', '#{escape_javascript(fields)}')"))
  end

  def skim_link(url, registrant_id = 0)
    url = url.strip()
    url = "http://" + url[8...url.length-8] if url.starts_with?("https://")
    url = "http://" + url unless url.start_with?("http://")

    begin
      host = URI.parse(url).host

      if host[/target.com\Z/]
        "http://gan.doubleclick.net/gan_click?lid=41000000000553798&pubid=21000000000564404&adurl=#{u(url)}"
      else
        "http://go.knackregistry.com/?id=29424X871720&xs=1&url=#{u(url)}&xcust=#{registrant_id}"
      end
    rescue
      url
    end
  end

  def contributor_names(item)
    if item.order_line_items.empty?
      ""
    elsif item.order_line_items.size == 1
      item.order_line_items.first.from
    else
      commaed_list = item.order_line_items - [item.order_line_items.last]
      "#{commaed_list.map(&:from).join(', ')} and #{item.contributes.last.From}"
    end
  end
end

skr/app/views/registrant/_registry_item.html.erb
<% item = i.object %>
<% available = item.Purchased_ID == RegistryItem::AVAILABLE %>


<li class="gift-entry<%= " gift-entry-purchased" if !available %>">
  <% unless edit%>
      <a href="<%=  from_registry_path(@registry.id, item.id, item.product.id, "item") %>">
  <% end %>
  <%= i.hidden_field :id %>
  <%= i.hidden_field :order, :class=>"order" %>
  <%= i.hidden_field :section_id, :class=>"section-id" %>
  <%= i.hidden_field :section_order, :class=>"section-order" %>
  <div class="gift-entry-image-box">
    <%= image_tag item.product.main_product_thumb.url(:medium), :alt => item.product.Name, :class => "product-image-medium" -%>
  </div>
  <div class="gift-entry-info">
    <span class='name'><%= item.product.Name %></span><br/>
      <span class='price'>
        <%= formatted_price(item.Price.to_f).to_s %>
      </span>
      <span class='status'>
        <%= formatted_remaining item %>
      </span>
  </div>
  <div class="buttons-left">
    <%= link_to from_registry_path(@registry.id, item.id, item.product.id, "item"), :class => "button-small" do %>
        VIEW
    <% end %>
  </div>
  <div class="buttons-top-right">
    <% if !edit && @registrant%>
        <a href="<%= add_from_registry_path item.id %>" data-id="<%=item.id%>" class="addfromregistry button-small">
          ADD TO MY REGISTRY
        </a>
    <% end %>
  </div>  <div class="buttons-right">
    <% if edit %>
        <%= link_to "#", :class => "move-item-up" do %>
            <%= image_tag "/images/pages/manage_registry/move_item_up.png", :alt => "Move Up" %>
        <% end %>

        <%= link_to "#", :class => "move-item-down" do %>
            <%= image_tag "/images/pages/manage_registry/move_item_down.png", :alt => "Move Down" %>
        <% end %>
    <% elsif available %>
        <% if !@registry.is_invited? %>
            <%= link_to "#", :class => "contribute button-small", :itemid => item.id do %>
                <%= item.allow_contribute? ? "BUY/CONTRIBUTE" : "BUY"%>
            <% end %>
        <% end %>
    <% end %>
  </div>
  <% unless edit%>
      </a>
  <% end %>
</li>

skr/app/views/registrant/add_from_registry.html.erb
<% content_for :header do %>
    <%= stylesheet_link_tag "/stylesheets/Global.css" %>
    <%= stylesheet_link_tag "/stylesheets/Pages/buy_contribute.css" %>
    <%= javascript_include_tag "/javascripts/jquery-1.4.2.min.js"  %>
    <%= javascript_include_tag "/javascripts/jquery.form.js"  %>
    <%= javascript_include_tag "/javascripts/jquery.keyfilter-1.7.js"  %>
    <%= javascript_include_tag "/javascripts/jquery.validate.js"  %>
    <%= javascript_include_tag "/javascripts/knack.registrant.edit_registry_item.js" %>
<% end %>

<%= form_for @reg_item, :url => add_from_registry_path(@orig_item_id) do |f| %>
    <%= f.error_messages %>
    <div class="pageName">
      <%= @reg_item.product.Name %>
    </div>
    <div class="buyTable">
      <table cellpadding="0px" cellspacing="0px" border="0">
        <tr>
          <td class="firstTD">
            <%= image_tag @reg_item.product.main_product_thumb.url(:medium),
                          :alt => @reg_item.product.Name,
                          :class => "product-image-medium",
                          :id => "product_image",
                          :name => "product_image" -%>
          </td>
          <td class="descriptionTD">

            <table>
              <% if @reg_item.product.cash? %>
                  <%= f.fields_for :product do |p| %>
                      <tr>
                        <td class="firstTD">
                          <%= p.label :Name %>
                        </td>
                        <td>
                          <%= p.text_field :Name%>
                        </td>
                      </tr>
                  <% end %>
              <% end %>
              <tr>
                <td class="firstTD">
                  <%= f.label :Quantity %>
                </td>
                <td>
                  <%= f.text_field :Quantity, :class => "required min=12", :readonly => @reg_item.product.unique?  %>
                </td>
              </tr>
              <% if @reg_item.product.cash? %>
                  <%= f.fields_for :product do |p| %>
                      <tr>
                        <td class="firstTD">
                          <%= f.label :Price, "Price"%>
                        </td>
                        <td>
                          <%= f.text_field :Price%>
                        </td>
                      </tr>
                  <% end %>
              <% else %>
                  <tr>
                    <td class="firstTD">
                      <label>Price</label>
                    </td>
                    <td>
                      <%= formatted_price(@reg_item.product.Price) %>
                    </td>
                  </tr>
              <% end %>

              <% unless @reg_item.product.colors.blank? %>
                  <tr>
                    <td class="firstTD">
                      <%= f.label :Color %>
                    </td>
                    <td>
                      <% if @reg_item.product.colors.count > 1 %>
                          <%= f.collection_select :Color_ID, @reg_item.product.colors.all, :id, :Name  %>
                      <% else %>
                          <%= @reg_item.product.colors[0].Name  %>
                          <%= f.hidden_field :Color_ID  %>
                      <% end %>
                    </td>
                  </tr>
              <% end %>

              <%#*------------------------%>
              <%#*Item Variants%>
              <%#*------------------------%>
              <% @reg_item.product.product_params.each do |p| %>
                  <tr>
                    <td class="firstTD">
                      <label><%= p.Name %></label>
                    </td>
                    <td>
                      <% if p.value_params.count > 1 %>
                          <%=  select("product_params", p.Name, p.get_select_values.collect {|v| [ v.Value, v.id ] }, :selected => @reg_item.get_product_params[p.Name]) %>
                      <% end %>
                    </td>
                  </tr>
              <%end%>
              <% if @reg_item.product.cash? %>
                  <%= f.fields_for :product do |p| %>
                      <tr>
                        <td class="firstTD">
                          <%= p.label :ext_color, "Color/Style"%>
                        </td>
                        <td>
                          <%= p.text_field :ext_color%>
                        </td>
                      </tr>
                      <tr>
                        <td class="firstTD">
                          <%= p.label :ext_size, "Size"%>
                        </td>
                        <td>
                          <%= p.text_field :ext_size%>
                        </td>
                      </tr>
                      <tr>
                        <td class="firstTD">
                          <%= p.label :ext_other, "Other Instructions"%>
                        </td>
                        <td>
                          <%= p.text_field :ext_other%>
                        </td>
                      </tr>
                  <% end %>
              <% end %>

            </table>
          </td>
        </tr>
      </table>
    </div>

    <div id="source">
      <label>Source:</label>
      <% if @reg_item.product.cash? %>
          <% if @reg_item.product.external? %>
              Guests will order this gift from
              <%= link_to @reg_item.product.source_name, skim_link(@reg_item.product.source_url, @registrant_id), :target => "_blank" %>
              <img src="/images/design/external_link.gif"/>
          <% else %>
              Guests will order this gift on Knack, you will receive cash to buy the gift.
          <% end %>
          <a id="edit-source-link" href="#">(change)</a>
      <% else %>
          Guests will order this gift on Knack from one of our partners.
      <% end %>
    </div>

    <% if @reg_item.product.cash? %>
        <%= f.fields_for :product do |p| %>
            <div id="edit-source" class="hidden group">
              <%= p.check_box :external%>
              <%= p.label :external, "Direct guests to an external site to buy this gift?"%>
              <dl>
                <dt>
                  <%= p.label :source_name, "Site Name"%>
                </dt>
                <dd>
                  <%= p.text_field :source_name%>
                </dd>

                <dt>
                  <%= p.label :source_url, "Link To Gift"%>
                </dt>
                <dd>
                  <%= p.text_field :source_url%>
                </dd>
              </dl>
            </div>
        <% end %>
    <% end %>

    <% if @reg_item.product.cash? %>
        <div class="description">
          <%= f.fields_for :product do |p| %>
              <div>
                <%= p.label :Description %>
              </div>
              <div>
                <%= p.text_area :Description%>
              </div>
          <% end %>
        </div>
    <% end %>
    <div class="actions">
      <%= f.submit "SAVE", :class=>"btn-save"  %>
    </div>
<% end %>

skr/app/views/registrant/home.html.erb
<% content_for :title do %>
    Unique Wedding Registry With Gifts You Wont Find At National Retailers
<% end %>
<% content_for :head do %>
    <link rel="canonical" href="https://knackregistry.com/" />
    <%= javascript_include_tag "/javascripts/knack.registrant.home.js"  %>
    <%= stylesheet_link_tag "/stylesheets/Pages/Home.css" %>
    <meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7"/>
    <meta name="description" content="Create a one of a kind wedding registry with traditional gifts, unique items, and honeymoon items on Knack."/>
    <meta name="msvalidate.01" content="9B8AAB462457A6739630E695B0BC0662" />
    <script type="text/javascript" src="https://fast.fonts.com/jsapi/1a1275b6-a264-4f4b-9d7c-e00caa86973f.js"></script>
<%  end %>
<% if Rails.env == "production" %>
    <!-- Google Code for Visit Home Page Remarketing List -->
    <script type="text/javascript">
        /* <![CDATA[ */
        var google_conversion_id = 1014910302;
        var google_conversion_language = "en";
        var google_conversion_format = "3";
        var google_conversion_color = "666666";
        var google_conversion_label = "X6XeCMK2tgIQ3pr54wM";
        var google_conversion_value = 0;
        /* ]]> */
    </script>
    <script type="text/javascript" src="https://www.googleadservices.com/pagead/conversion.js">
    </script>
    <noscript>
      <div style="display:inline;">
        <img height="1" width="1" style="border-style:none;" alt="" src="https://www.googleadservices.com/pagead/conversion/1014910302/?label=X6XeCMK2tgIQ3pr54wM&amp;guid=ON&amp;script=0"/>
      </div>
    </noscript>
<% end %>

<div class="div-c">
  <div id="page-container">
    <div id="heroboard_container">
      <div id="static">
        <div id="heroboard_text">
          <h1 class="heroboard_headline">Build a list.<br>Share it.<br>Raise Money.</h1>
          <h2 class="heroboard_copy">A free service that makes it easy to collect payments from family and friends.</h2>
        </div>
        <div id="heroboard_image_container">
          <a id="heroboard_image">
            <img src="/images/pages/home/hero_image.png" alt="create a more personalized and unique wedding registry with Knack"/>
          </a>
        </div>
      </div>
      <div id="video">
      </div>
      <div id="learn_more">
        <a href="/info/tour"><img src="/images/pages/home/learn_more_lrg.png" width="147" height="32" alt="Learn More"  border="0"/></a>
        <a href="/signup"><img src="/images/pages/home/sign_up_lrg.png" width="162" height="32" alt="Sign-up now" border="0"/></a>
      </div>
    </div>

    <div id='home-calls-for-action'>
      <table id="tbl-home">
        <tbody>
          <tr>
            <td>
              <div class="home-block" id="create-registry">
                <div class="in-block">
                  <p><span id="spn-crreg">Raise Money</span></p>
                </div>
                <a href="<%= signup_path %>">
                  <div class="btn-in-block" id="div-btn-sign"></div>
                </a>
              </div>
            </td>
            <td>
              <div class="home-block" id="find-registry">
                <div class="in-block">
                  <p><span id="spn-fndreg">Find Friends and Family</span></p>
                  <p><span class="spn-text-in">Make payments towards whatever is most meaningful to those closest to you for free.</span></p>
                  <form id="frm-home-find" action="<%= give_path %>" method="get">
                    <input type="text" id="find" name="find"/>
                    <a id="a-find" href="/">
                      <div class="btn-in-block" id="div-btn-find">
                      </div>
                    </a>
                    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" />
                  </form>
                </div>
              </div>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>

</div>

skr/app/views/registrant/login.html.erb
<% content_for :title do %>
  Login | Knack Registry
<% end %>
<% content_for :head do %>
  <%= stylesheet_link_tag "/stylesheets/Pages/Login.css" %>
  <%= javascript_include_tag "/javascripts/knack.registrant.login.js"  %>
<%  end %>


  <div class="div-container-login">
          <div class="pageName">
            Login
          </div>
          <div>
            <%= form_tag signin_path do%>
              <div id="div-login">
                <div class="div-block">
                  <div class="editor-label">
                    <label for="Email">Email</label>
                  </div>
                  <div class="editor-field">
                    <%=text_field :registrant, 'Email'-%>

                  </div>
                  <div class="editor-error">
                    <span class="formError"><%= @err_email %></span>
                  </div>
                </div>

                <div class="div-block">
                  <div class="editor-label">
                        <label for="Password">Password</label>
                  </div>
                  <div class="editor-field">
                    <%=password_field :registrant, :Password-%>

                  </div>
                  <div class="editor-error">
                    <span class="formError"><%= @err_pass %></span>
                  </div>
                </div>

                <div class="div-block">
                  <div id="forgotPas" class="editor-label">
                    <a href="/registrant/forgotpassword" >Forgot Password?</a>
                  </div>
                  <div id="remember" class="editor-field">
                    <%= check_box_tag 'rememberMe', 'yes', false %>Remember me
                  </div>
                </div>

                <div class="div-block">
                  <div id="register" class="editor-label">
                    <a href="<%= signup_path %>" >Not a member? Register!</a>
                  </div>
                  <div id="logButton" class="editor-field">
                    <%=submit_tag 'Login'-%>
                  </div>
                </div>



                <div class="formError div-generr"><%= @err_general %></div>

              </div>
            <%end%>
          </div>

          <div class="div-block">
            <div class="line"></div>


            <div class="facebookBlock">
              Login using Facebook:

              <div class="faceBut">
                <a id="fb-login" href="#">
                  <img src = "/images/general/social/fb-login.png"/>
                </a>
                <span id="login_spinner" style="position:absolute;padding-top:2px;padding-left:5px;display:none"><img src="/images/spinner.gif" alt="" /></span>
              </div>
            </div>
          </div>



</div>
  <div class="clearfloat"></div>


<%= render :partial => 'shared/fb_init' %>