skr/config/routes.rb
KnackRegistry::Application.routes.draw do

  root :to => "registrant#home"

  match 'signin' => "registrant#login"
  match 'signout' => "registrant#logout"
  match 'signup' => "registrant#register"
  match 'give' => "registrant#give"

  match 'profile' => "registrant#profile"
  match 'transactions' => "registrant#viewall"
  match 'addgift' => "registrant#addgift"
  match 'links' => "registrant#links"
  match 'manage_registry' => "registrant#manage_registry"
  match 'invite_friends' => "follows#index"
  match 'fetch_fb_cross_friends' => "registrant#fetch_fb_cross_friends"
  match 'invited_signup' => 'registrant#invited_signup'

  match 'purchased' => redirect("/manage_registry")
  match 'wishlist' => redirect("/manage_registry")
  match 'ordered' => redirect("/manage_registry")

  match 'add_to_cart/:id' => "registrant#add_to_cart"
  match 'registrant/exchange/:id' => "registrant#exchange"

  match 'toolbars' => 'registrant#downloadtool'
  match 'add_my_gift' => 'registrant#addmyowngift', :as => 'add_my_gift'
  match 'use_toolbar' => 'registrant#how_use_toolbar'
  match 'calculate_tax' => 'registrant#calculate_tax'
  match 'delete_registry_item/:id' => 'registrant#delete_registry_item', :as => 'delete_registry_item'
  match 'edit_registry_item/:id' => 'registrant#edit_registry_item', :as => 'edit_registry_item'
  match 'add_from_registry/:id' => 'registrant#add_from_registry', :as => 'add_from_registry'

  match 'home' => redirect("/")
  match 'home2' => redirect("/")
  match 'home3' => redirect("/")
  match 'registrant/home' => redirect("/")
  match 'registry/:id' => 'registrant#registry', :as => 'registry'
  match 'catalog(/:id)' => 'browse#catalog', :as => 'catalog'
  match 'hot(/:site)' => 'browse#feed', :as => 'feed'

  match 'cart' => "payment#cart"
  get   'select_payment_method' => 'payment#select_payment_method'
  get   'pay_via_check' => 'payment#pay_via_check'
  get   'pay_via_venmo' => 'payment#pay_via_venmo'
  post  'make_payment_via_venmo' => 'payment#make_payment_via_venmo'
  match 'step1(/:id)' => "payment#step1", :as => "step1"
  match 'step2(/:id)' => "payment#step2", :as => 'step2'
  match 'step3' => "payment#step3"
  match 'process_order' => "payment#process_order"
  match 'success_payment/:guid' => "payment#success_payment", :as => "success_payment"
  match 'error_payment/:message' => "payment#error_payment", :as => "error_payment"
  match 'payment_interrupted' => "payment#payment_interrupted", :as => "payment_interrupted"

  scope 'item' do
    match ':c/:id(/:item_name)' => 'browse#item', :as => 'from_catalog'
    match ':r/:r2p/:id(/:item_name)' => 'browse#item', :as => 'from_registry'
  end

  match 'brands' => 'browse#brands'
  match 'brand/:valparam' => 'browse#catalog', :defaults => {:param => "b"}, :as => 'brand'
  match 'brand/:b/:id' => 'browse#item', :as => 'from_brand'

  match 'stores' => 'browse#stores'
  match 'store/:valparam' => 'browse#catalog', :defaults => {:param => "s"}, :as => 'store'
  match 'store/:s/:id' => 'browse#item', :as => 'from_store'

  match 'sf' => redirect("/sanfrancisco")
  match 'san_francisco' => redirect("/sanfrancisco")
  match 'sanfrancisco' => 'info#san_francisco'

  match 'info/sample_registry' => redirect("/sample_registry")
  match 'sample_registry' => 'registrant#registry', :defaults => {:id => 644}

  match 'info/howdoeswork' => redirect("/info/tour")

  resources :follows, :only => [:index, :create, :destroy, :follow_fb_friends]

  namespace :admin do
    resources :products, :except => :destroy do
      member do
        get :image
        put :image
      end
    end
    resources :partner_administrators do
      member do
        get :delete
      end
    end
  end

  match ':controller(/:action(/:id))'

end

skr/app/views/layouts/_analytics.html.erb
<script type="text/javascript">

    var _gaq = _gaq || [];
    <% if Rails.env == "production" %>
    _gaq.push(['_setAccount', 'UA-20440452-1']);
    _gaq.push(['_setDomainName', 'knackregistry.com']);
    _gaq.push(['_trackPageview']);

    (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
    <% end %>
</script>

skr/app/views/layouts/_cat-wrapper.html.erb
<div id="cat-wrapper" class="tag-none" style="filter:alpha(opacity=50); -moz-opacity:.50; opacity:.50;">
  <div id="cat-container">
    <img alt="" src="/images/wait.gif" />
  </div>
</div>

skr/app/views/layouts/_footer.html.erb
<div id="footer">
  <table id="tbl-footer">
    <tbody>
    <tr>
      <td id="fmw">
        <table id="footer-menu-wrapper">
          <tr>
            <td><a href="/info/aboutus">About Knack</a></td>
            <td><a href="/info/policy">Site Policy</a></td>
          </tr>
          <tr>
            <td><a href="/info/tour">Tour</a></td>
            <td></td>
            <td></td>
            <td><a href="/partner/partnerslogin">Partner Login</a></td>
          </tr>
          <tr>
            <td><a href="http://knackregistry.zendesk.com">FAQ</a></td>
            <td></td>
          </tr>
        </table>
      </td>
      <td>
      </td>
      <td>
        <a target="_blank" id="bbblink" class="sehzbus" href="http://www.bbb.org/greater-san-francisco/business-reviews/internet-shopping/knack-in-san-francisco-ca-388285#bbblogo" title="Knack LLC, Internet Shopping, San Francisco, CA" style="display: block;position: relative;overflow: hidden; width: 100px; height: 38px; margin: 0px; padding: 0px;"><img style="padding: 0px; border: none;" id="bbblinkimg" src="https://seal-goldengate.bbb.org/logo/sehzbus/knack-388285.png" width="200" height="38" alt="Knack LLC, Internet Shopping, San Francisco, CA" /></a><script type="text/javascript">var bbbprotocol = ( ("https:" == document.location.protocol) ? "https://" : "http://" ); document.write(unescape("%3Cscript src='" + bbbprotocol + 'seal-goldengate.bbb.org' + unescape('%2Flogo%2Fknack-388285.js') + "' type='text/javascript'%3E%3C/script%3E"));</script>
      </td>
      <td>
        <div id="div-tf">
          <a href="http://www.facebook.com/pages/Knackregistrycom/118149381538155"><img src="/images/design/facebook.png" class="tf" alt="facebook"/></a>
        </div>
      </td>
    </tr>
    </tbody>
  </table>
</div>

skr/app/views/layouts/_snap_engage.erb
<% if Rails.env == "production" || Rails.env == "preview" %>
    <script type="text/javascript">
        document.write(unescape("%3Cscript src='" + ((document.location.protocol=="https:")?"https://snapabug.appspot.com":"http://www.snapengage.com") + "/snapabug.js' type='text/javascript'%3E%3C/script%3E"));</script><script type="text/javascript">
        SnapABug.addButton("2b0eb56c-6f6d-44fb-a622-76d3ec33af66","0","350px");
    </script>
<% end %>

skr/app/views/layouts/access.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <link rel="shortcut icon" href="/images/fav.gif" />
  <meta http-equiv="Content-Type" content="text/xhtml; charset='utf-8'"></meta>
  <style type="text/css">
 
    #login-site
    {
        margin: 25% auto;
        width: 200px;
        position: relative;
    }
    #login-site input
    {
      margin-bottom: 10px;
}
#login-site input[type=text], input[type=password]
{
  width: 200px;
}
  </style>
  <%= render :partial => 'layouts/analytics' %>
</head>
<body>
  <div id="wrapper">
    <%= yield %>
 </div>
 <%= render "layouts/snap_engage" %>
</body>
</html>

skr/app/views/layouts/admin.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:og="http://opengraphprotocol.org/schema/">

<head>
  <link rel="shortcut icon" href="/images/fav.gif" />
  <%= stylesheet_link_tag "/stylesheets/layouts/Partners.css" %>
  <%= stylesheet_link_tag "/stylesheets/Global.css" %>
  <%= stylesheet_link_tag "/stylesheets/Controls/UpdateProgress.css" %>
  <%= javascript_include_tag "/javascripts/jquery-1.4.2.min.js"  %>
  <%= javascript_include_tag "/javascripts/hide_menu.js"  %>
  <%= javascript_include_tag "/javascripts/jQuery.timer.js"  %>
  <%= javascript_include_tag "/javascripts/knack.global.js"  %>
  <%= javascript_tag "var AUTH_TOKEN = #{form_authenticity_token.inspect};" if protect_against_forgery? %>
  <title><%= yield :title %></title>
  <%= yield :head %>
  <%= render :partial => 'layouts/analytics' %>
</head>
<body>
<%= yield :under_body %>
<div id="helper"></div>
<div id="wrapper" class="redBorder">


    <div id="header">
      <table>
        <tbody>
          <tr>
            <td>
              <a href="/"><img alt="" id="logo" alt="logo" src="/images/design/logo.gif"/></a>
            </td>
            <td>
              <div id="navbar">
            <table id="tbl-nav">
              <tr>
                <td>
                  <ul>
                    <li>
                      <%= link_to @is_admin ? "/administrative/profile" : "/partner/partnerprofile" do %>
                        <div id="dm-home" class="menu-block">
                          <span class="b5">Home</span>
                        </div>
                      <% end %>
                    </li>
                    <li>
                      <%= link_to @is_admin ? "/administrative/orders" : "/partner/orders" do %>
                        <div id="dm-give" class="menu-block">
                          <span class="b5">Orders</span>
                        </div>
                      <% end %>
                    </li>

                    <li>
                      <%= link_to admin_products_path do %>
                        <div id="dm-receive" class="menu-block">
                          <span class="b5">Products</span>
                        </div>
                      <% end %>
                    </li>

                    <% if @is_admin %>
                        <li>
                          <a href="/administrative/categorylist">
                            <div id="dm-browse" class="menu-block">
                              <span class="b5">Categories</span>
                            </div>
                          </a>
                        </li>
                    <% else %>
                        <li>
                          <a href="/partner/knackpayments">
                            <div id="dm-browse" class="menu-block">
                              <span class="b5">Payments</span>
                            </div>
                          </a>
                        </li>
                    <% end %>
                  </ul>
                </td>
                <td>
                  <%if session[:knack].blank? && session[:partner].blank? %>
                    <div id="div-rl">
                      <a href="/administrative/register">Sign Up</a> |
                      <a href="/administrative/login">Sign In</a>
                    </div>
                  <% else %>
                    <div id="div-rl">
                      <%= link_to @is_admin ? "/administrative/profile" : "/partner/partnerprofile" do %>
                          <%= @current_partner.display_name %>
                      <% end %>
                      |
                      <%= link_to @is_admin ? "/administrative/logout" : "/partner/partnerslogout" do %>
                          Sign Out
                      <% end %>
                    </div>
                  <% end %>
                </td>
                </tr>
              <tr id="gr"><td></td><td></td><td></td></tr>
              </table>
            </div>
            </td>

            <td>
               <div id="menu_holder">
                 <form id="frm-top-find" action="/registrant/give" method="post">
                   <input id="it-find" name="find" type="text"/>
                   <a id="btn-find-top" href="/">
                     <div id="div-btn-find-top"></div>
                   </a>
                    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" />
                  </form>

               </div>
             </td>
            </tr>
         </tbody>
      </table>

    </div>


    <div id="content" >
      <div class="div-c">

        <%#*--------------------------------%>
        <%#*Top Menu%>
        <%#*--------------------------------%>

        <div class="topMenu">
          <table cellpadding="0px" cellspacing="0px">
            <tr>
              <td class="pageNameTD">
                <%= yield :pagename %>
              </td>
              <td class="topMenuTD">
                <% unless @partner.blank? %>
                    <div class="div-user-menu">
                      <% if @is_admin%>
                          <a href="/administrative/canceled_payments">Canceled Orders</a>
                          <a href="/administrative/partners">Partners</a>
                          <a href="/administrative/stores">Stores</a>
                          <%= link_to "Administrators", admin_partner_administrators_path %>
                          <a href="/administrative/registrants">Registries</a>
                          <a href="/administrative/colors">Colors</a>
                          <a href="/administrative/statistics">Statistics</a>
                      <% else %>
                          <a href="/partner/storeslist">Stores</a>
                          <%= link_to "Administrators", admin_partner_administrators_path %>
                      <% end %>
                    </div>
                    <%= yield :completemenu %>
                <% end %>
              </td>
            </tr>
            <tr>
              <td class="registry">
                <div class="empty-padding"></div>
                <%= yield :registry %>
              </td>
              <td class="registry">
                <div class="empty-padding"></div>
                <%= yield :background %>
              </td>
            </tr>
          </table>
        </div>

        <%#*--------------------------------%>
        <%#*Content%>
        <%#*--------------------------------%>

              <%= yield %>
      </div>
    </div>

  </div>
<%= render :partial => 'layouts/footer' %>

<%= render :partial => 'layouts/cat-wrapper' %>
<%= render "layouts/snap_engage" %>
</body>

</html>

skr/app/views/layouts/administrative.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:og="http://opengraphprotocol.org/schema/">

<head>
  <link rel="shortcut icon" href="/images/fav.gif" />
  <%= stylesheet_link_tag "/stylesheets/layouts/Partners.css" %>
  <%= stylesheet_link_tag "/stylesheets/Global.css" %>
  <%= stylesheet_link_tag "/stylesheets/Controls/UpdateProgress.css" %>
  <%= javascript_include_tag "/javascripts/jquery-1.4.2.min.js"  %>
  <%= javascript_include_tag "/javascripts/hide_menu.js"  %>
  <%= javascript_include_tag "/javascripts/jQuery.timer.js"  %>
  <%= javascript_include_tag "/javascripts/knack.global.js"  %>
  <%= javascript_tag "var AUTH_TOKEN = #{form_authenticity_token.inspect};" if protect_against_forgery? %>
  <title><%= yield :title %></title>
  <%= yield :head %>
  <%= render :partial => 'layouts/analytics' %>
</head>
<body>
<%= yield :under_body %>
<div id="helper"></div>
<div id="wrapper" class="redBorder">


    <div id="header">
      <table>
        <tbody>
          <tr>
            <td>
              <a href="/registrant/home"><img alt="" id="logo" alt="logo" src="/images/design/logo.gif"/></a>
            </td>
            <td>
              <div id="navbar">
            <table id="tbl-nav">
              <tr>
                <td>
                  <ul>
                    <li>
                      <a href="/administrative/profile">
                        <div id="dm-home" class="menu-block">
                          <span class="b5">Home</span>
                        </div>
                      </a>
                    </li>
                    <li>
                      <a href="/administrative/orders">
                        <div id="dm-give" class="menu-block">
                          <span class="b5">Orders</span>
                        </div>
                      </a>
                    </li>

                    <li>
                      <%= link_to admin_products_path do %>
                          <div id="dm-receive" class="menu-block">
                            <span class="b5">Products</span>
                          </div>
                      <% end %>
                    </li>

                    <li>
                      <a href="/administrative/categorylist">
                        <div id="dm-browse" class="menu-block">
                          <span class="b5">Categories</span>
                        </div>
                      </a>
                    </li>
                  </ul>
                </td>
                <td>
                  <%if session[:knack].blank? %>
                    <div id="div-rl">
                      <a href="/administrative/register">Sign Up</a> |
                      <a href="/administrative/login">Sign In</a>
                    </div>
                  <% else %>
                    <div id="div-rl">
                          <a href="/administrative/profile"><%= @current_partner.display_name -%></a> |
                          <a href="/administrative/logout">Sign Out</a>
                    </div>
                  <% end %>
                </td>
                </tr>
              <tr id="gr"><td></td><td></td><td></td></tr>
              </table>
            </div>
            </td>

            <td>
               <div id="menu_holder">
                 <form id="frm-top-find" action="/registrant/give" method="post">
                   <input id="it-find" name="find" type="text"/>
                   <a id="btn-find-top" href="/">
                     <div id="div-btn-find-top"></div>
                   </a>
                    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" />
                  </form>

               </div>
             </td>
            </tr>
         </tbody>
      </table>

    </div>


    <div id="content" >
      <div class="div-c">

        <%#*--------------------------------%>
        <%#*Top Menu%>
        <%#*--------------------------------%>

        <div class="topMenu">
          <table cellpadding="0px" cellspacing="0px">
            <tr>
              <td class="pageNameTD">
                <%= yield :pagename %>
              </td>
              <td class="topMenuTD">
                <div class="div-user-menu">
                  <a href="/administrative/canceled_payments">Canceled Orders</a>
                  <a href="/administrative/partners">Partners</a>
                  <a href="/administrative/stores">Stores</a>
                  <%= link_to "Administrators", admin_partner_administrators_path %>
                  <a href="/administrative/registrants">Registries</a>
                  <a href="/administrative/colors">Colors</a>
                  <a href="/administrative/statistics">Statistics</a>
                </div>
                <%= yield :completemenu %>
              </td>
            </tr>
            <tr>
              <td class="registry">
                <div class="empty-padding"></div>
                <%= yield :registry %>
              </td>
              <td class="registry">
                <div class="empty-padding"></div>
                <%= yield :background %>
              </td>
            </tr>
          </table>
        </div>

        <%#*--------------------------------%>
        <%#*Content%>
        <%#*--------------------------------%>

              <%= yield %>
      </div>
    </div>

  </div>
<%= render :partial => 'layouts/footer' %>

<%= render :partial => 'layouts/cat-wrapper' %>
<%= render "layouts/snap_engage" %>
</body>

</html>

skr/app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:og="http://opengraphprotocol.org/schema/">
	<head>
	  <link rel="shortcut icon" href="/images/fav.gif" />
	  <%= stylesheet_link_tag "/stylesheets/application.css" %>
	  <%= stylesheet_link_tag "/stylesheets/Global.css" %>
	  <%= stylesheet_link_tag "/stylesheets/Controls/UpdateProgress.css" %>
	  <%= javascript_include_tag "/javascripts/jquery-1.4.4.min.js"  %>
	  <%= javascript_include_tag "/javascripts/hide_menu.js"  %>
	  <%= javascript_include_tag "/javascripts/jQuery.timer.js"  %>
	  <%= javascript_include_tag "/javascripts/knack.global.js"  %>
	  <%= javascript_tag "var AUTH_TOKEN = #{form_authenticity_token.inspect};" if protect_against_forgery? %>
	  <title><%= yield :title %></title>
	  <%= yield :head %>
	  <meta http-equiv="Content-Type" content="text/xhtml; charset='utf-8'"/>
      <%= render :partial => 'layouts/analytics' %>
	</head>
	<body>
    <%= yield :under_body %>
		<div id="helper"></div>
		<div id="wrapper" class="redBorder">
	    <div id="header">
	      <table>
	        <tbody>
	          <tr>
	            <td>
	              <a href="<%= home_path %>"><img id="logo" alt="Knack" src="/images/design/logo.gif"/></a>
	            </td>
	            <td>
	              <div id="navbar">
		            	<table id="tbl-nav">
			              <tr>
			                <td class="nav">
			                  <% if session[:full_nav] || session[:registrant] %>
                                  <ul>
                                    <li>
                                      <a href="<%= home_path %>">
                                        <div id="dm-home" class="menu-block">
                                          <span class="b5">HOME</span>
                                        </div>
                                      </a>
                                    </li>
                                    <li>
                                      <a href="<%= feed_path %>">
                                        <div id="dm-browse" class="menu-block">
                                          <span class="b5">WHAT'S HOT</span>
                                        </div>
                                      </a>
                                    </li>
                                    <li>
                                      <a href="<%= give_path %>">
                                        <div id="dm-give" class="menu-block">
                                          <span class="b5">GIVE</span>
                                        </div>
                                      </a>
                                    </li>
                                    <li>
                                      <%= link_to (session[:registrant].blank? ? signin_path : manage_registry_path) do %>
                                          <div id="dm-receive" class="menu-block">
                                            <span class="b5">RECEIVE</span>
                                          </div>
                                      <% end %>
                                    </li>
                                  </ul>
                              <% end %>
			                </td>
                            <td>
                              <div id="div-rl">
                                <% if session[:registrant].blank? %>
                                    <a href="<%= signin_path %>">Sign In</a>
                                    | <a href="<%= signup_path %>"> Sign Up </a>
                                <% else %>
                                    <a href="<%= profile_path %>"><%= @current_user.display_name -%></a> |
                                    <a href="<%= signout_path %>">Sign Out</a>
                                <% end %>
                              </div>
                            </td>
                            <td>
                              <div id="div-fb">
                                <a href="<%= cart_path %>"><img src="/images/design/cart.png" alt="cart"/></a>
                              </div>
                            </td>			              </tr>
			              <tr id="gr"><td></td><td></td><td></td></tr>
			            </table>
		            </div>
	            </td>
	          </tr>
	        </tbody>
	      </table>
	    </div>

	    <div id="content">
	      <%= yield %>
	    </div>
	  </div>

		<%= render :partial => 'layouts/footer' %>

        <%= render :partial => 'layouts/cat-wrapper' %>

        <%= render "layouts/snap_engage" %>
	</body>
</html>

skr/app/views/layouts/givers.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <link rel="shortcut icon" href="/images/fav.gif" />

  <%= render :partial => 'layouts/analytics' %>
</head>
<body>
  <div id="wrapper">
    <%= yield %>
 </div>
</body>
</html>

skr/app/views/layouts/registrant.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:og="http://opengraphprotocol.org/schema/">
<head>
  <link rel="shortcut icon" href="/images/fav.gif" />
  <%= stylesheet_link_tag "/stylesheets/layouts/Registrant.css" %>
  <%= stylesheet_link_tag "/stylesheets/Global.css" %>
  <%= stylesheet_link_tag "/stylesheets/Controls/UpdateProgress.css" %>
  <%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"  %>
  <%= javascript_include_tag "/javascripts/hide_menu.js"  %>
  <%= javascript_include_tag "/javascripts/jQuery.timer.js"  %>
  <%= javascript_include_tag "/javascripts/knack.global.js"  %>
  <%= javascript_tag "var AUTH_TOKEN = #{form_authenticity_token.inspect};" if protect_against_forgery? %>
  <title><%= yield :title %></title>
  <%= yield :head %>
  <%= render :partial => 'layouts/analytics' %>
</head>
<body>
<%= yield :under_body %>
<div id="helper"></div>
<div id="wrapper" class="redBorder">
  <div id="header">
    <table>
      <tbody>
      <tr>
        <td>
          <a href="<%= home_path %>"><img id="logo" alt="Knack" src="/images/design/logo.gif"/></a>
        </td>
        <td>
          <div id="navbar">
            <table id="tbl-nav">
              <tr>
                <td class="nav">
                  <% if session[:full_nav] || session[:registrant] %>
                      <ul>
                        <li>
                          <a href="<%= home_path %>">
                            <div id="dm-home" class="menu-block">
                              <span class="b5">HOME</span>
                            </div>
                          </a>
                        </li>
                        <li>
                          <a href="<%= feed_path %>">
                            <div id="dm-browse" class="menu-block">
                              <span class="b5">WHAT'S HOT</span>
                            </div>
                          </a>
                        </li>
                        <li>
                          <a href="<%= give_path %>">
                            <div id="dm-give" class="menu-block">
                              <span class="b5">GIVE</span>
                            </div>
                          </a>
                        </li>
                        <li>
                          <%= link_to(session[:registrant].blank? ? signin_path : manage_registry_path) do %>
                              <div id="dm-receive" class="menu-block">
                                <span class="b5">RECEIVE</span>
                              </div>
                          <% end %>
                        </li>
                      </ul>
                  <% end %>
                </td>
                <td>
                  <div id="div-rl">
                    <% if session[:registrant].blank? %>
                        <a href="<%= signin_path %>">Sign In</a>
                        | <a href="<%= signup_path %>"> Sign Up </a>
                    <% else %>
                        <a href="<%= profile_path %>"><%= @current_user.display_name -%></a> |
                        <a href="<%= signout_path %>">Sign Out</a>
                    <% end %>
                  </div>
                </td>
                <td>
                  <div id="div-fb">
                    <a href="<%= cart_path %>"><img src="/images/design/cart.png" alt="cart"/></a>
                  </div>
                </td>
              </tr>
              <tr id="gr"><td></td><td></td><td></td></tr>
            </table>
          </div>
        </td>
      </tr>
      </tbody>
    </table>
  </div>

  <div id="content" >
    <%= yield :catalog %>
    <div class="div-c">

      <%#*--------------------------------%>
      <%#*Top Menu%>
      <%#*--------------------------------%>

      <div class="topMenu">
        <table cellpadding="0" cellspacing="0">
          <tr>
            <td class="pageNameTD">
              <%= yield :pagename %>
            </td>
            <td class="topMenuTD">
              <% if !session[:registrant].blank? %>
                  <% if !@registrant.blank? %>
                      <div class="div-user-menu">
                        <a href="<%= addgift_path %>">Add Gift</a>
                        <a href="<%= manage_registry_path %>">Manage Registry</a>
                        <a href="<%= registry_path(@registrant) %>">View Registry</a>
                        <img id="your-friends-icon" src="/images/general/social/fb_small.png"/>
                        <a href="<%=invite_friends_path%>">Your Friends</a>
                        <% if !@registrant.is_invited? %>
                            <a href="<%= links_path %>">Share</a>
                        <% end %>
                      </div>
                  <% end %>
                  <%= yield :completemenu %>
              <% end %>
            </td>
          </tr>
          <tr class="second-tr-top-menu">
            <td class="registry">
              <div class="empty-padding"></div>
              <div class="bl-block">
                <div class="blue-line">
                  <div class="registrants">
                    <%= yield :registry %>
                  </div>
                  <%= yield :manage %>
                </div>
              </div>
            </td>
            <td class="registry">
              <div class="empty-padding"></div>
              <div class="bl-block">
                <div class="blue-line">
                  <input type="hidden" value="fghj"/>
                  <%= yield :background %>
                </div>
              </div>
            </td>
          </tr>
        </table>
      </div>

      <%#*--------------------------------%>
      <%#*Content%>
      <%#*--------------------------------%>
      <%= yield %>
    </div>
  </div>

</div>
<%= render :partial => 'layouts/footer' %>

<%= render :partial => 'layouts/cat-wrapper' %>

<%= render "layouts/snap_engage" %>
</body>
</html>